# Generated by Django 5.2.16 on 2026-07-19 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='cultivo_en_lote',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='lote',
        ),
        migrations.CreateModel(
            name='ActividadLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hectareas', models.FloatField(default=0)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.actividad')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lote')),
            ],
            options={
                'unique_together': {('actividad', 'lote')},
            },
        ),
        migrations.AddField(
            model_name='actividad',
            name='lotes',
            field=models.ManyToManyField(through='api.ActividadLote', to='api.lote'),
        ),
        migrations.CreateModel(
            name='PrecioProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_vigencia', models.DateField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='api.producto')),
            ],
            options={
                'ordering': ['-fecha_vigencia'],
            },
        ),
    ]
