# Generated by Django 4.2 on 2026-07-24 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_lote_usuario_producto_usuario'),
    ]

    operations = [
    ]
